# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  restaurant:
    image: restaurant
    build:
      context: .
      dockerfile: Resturent/Dockerfile
    ports:
      - 44342:44342
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
